###
GET http://localhost:4000/api/users

###
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "nombre": "Pau",
    "apellidos": "Callejas Tovar",
    "email": "a18paucaltov@inspedralbes.cat",
    "password": "123456"
}